services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=item'
      - 'MYSQL_PASSWORD=itempassword'
      - 'MYSQL_ROOT_PASSWORD=itempassword'
      - 'MYSQL_USER=itemuser'
    ports:
      - '13306:3306'
    volumes:
      - ./init_db/docker-entrypoint-initdb.d
